import type { Voice } from './types.js';

// Official TTS 2.0 table, verified 2026-10-01. Short names are chat command aliases.
// https://docs.volcengine.com/docs/DoubaoVoice/Tonelist-1?lang=zh
const catalog = `Vivi|female|vv|通用场景
小何|female|xiaohe|通用场景
云舟|male|m191|通用场景
小天|male|taocheng|通用场景
刘飞|male|liufei|通用场景
魅力苏菲|female|sophie|通用场景
清新女声|female|qingxinnvsheng|通用场景
知性灿灿|female|cancan|角色扮演
撒娇学妹|female|sajiaoxuemei|角色扮演
甜美小源|female|tianmeixiaoyuan|通用场景
甜美桃子|female|tianmeitaozi|通用场景
爽快思思|female|shuangkuaisisi|通用场景
佩奇猪|female|peiqi|视频配音
邻家女孩|female|linjianvhai|通用场景
少年梓辛|male|shaonianzixin|通用场景
猴哥|male|sunwukong|视频配音
Tina老师|female|yingyujiaoxue|教育场景
暖阳女声|female|kefunvsheng|客服场景
儿童绘本|female|xiaoxue|有声阅读
大壹|male|dayi|视频配音
黑猫侦探社咪仔|female|mizai|视频配音
鸡汤女|female|jitangnv|视频配音
魅力女友|female|meilinvyou|通用场景
流畅女声|female|liuchangnv|视频配音
儒雅逸辰|male|ruyayichen|视频配音
温柔妈妈|female|wenroumama|通用场景
解说小明|male|jieshuoxiaoming|通用场景
TVB女声|female|tvbnv|通用场景
译制片男|male|yizhipiannan|通用场景
俏皮女声|female|qiaopinv|通用场景
直率英子|female|zhishuaiyingzi|角色扮演
邻家男孩|male|linjiananhai|通用场景
四郎|male|silang|角色扮演
儒雅青年|male|ruyaqingnian|通用场景
擎苍|male|qingcang|角色扮演
熊二|male|xionger|角色扮演
樱桃丸子|female|yingtaowanzi|角色扮演
温暖阿虎|male|wennuanahu|通用场景
奶气萌娃|male|naiqimengwa|通用场景
婆婆|female|popo|通用场景
高冷御姐|female|gaolengyujie|通用场景
傲娇霸总|male|aojiaobazong|通用场景
懒音绵宝|male|lanyinmianbao|角色扮演
反卷青年|male|fanjuanqingnian|通用场景
温柔淑女|female|wenroushunv|通用场景
古风少御|female|gufengshaoyu|角色扮演
活力小哥|male|huolixiaoge|通用场景
霸气青叔|male|baqiqingshu|有声阅读
悬疑解说|male|xuanyijieshuo|有声阅读
萌丫头|female|mengyatou|通用场景
贴心女声|female|tiexinnvsheng|通用场景
鸡汤妹妹|female|jitangmei|通用场景
磁性解说男声|male|cixingjieshuonan|通用场景
亮嗓萌仔|male|liangsangmengzai|通用场景
开朗姐姐|female|kailangjiejie|通用场景
高冷沉稳|male|gaolengchenwen|通用场景
深夜播客|male|shenyeboke|通用场景
鲁班七号|male|lubanqihao|角色扮演
娇喘女声|female|jiaochuannv|通用场景
林潇|female|linxiao|角色扮演
玲玲姐姐|female|lingling|角色扮演
春日部姐姐|female|chunribu|角色扮演
唐僧|male|tangseng|角色扮演
庄周|male|zhuangzhou|角色扮演
开朗弟弟|male|kailangdidi|通用场景
猪八戒|male|zhubajie|角色扮演
感冒电音姐姐|female|ganmaodianyin|角色扮演
谄媚女声|female|chanmeinv|通用场景
女雷神|female|nvleishen|角色扮演
亲切女声|female|qinqienv|通用场景
快乐小东|male|kuailexiaodong|通用场景
开朗学长|male|kailangxuezhang|通用场景
悠悠君子|male|youyoujunzi|通用场景
文静毛毛|female|wenjingmaomao|通用场景
知性女声|female|zhixingnv|通用场景
清爽男大|male|qingshuangnanda|通用场景
渊博小叔|male|yuanboxiaoshu|通用场景
阳光青年|male|yangguangqingnian|通用场景
清澈梓梓|female|qingchezizi|通用场景
甜美悦悦|female|tianmeiyueyue|通用场景
心灵鸡汤|female|xinlingjitang|通用场景
温柔小哥|male|wenrouxiaoge|通用场景
柔美女友|female|roumeinvyou|通用场景
东方浩然|male|dongfanghaoran|通用场景
温柔小雅|female|wenrouxiaoya|通用场景
天才童声|male|tiancaitongsheng|通用场景
武则天|female|wuzetian|角色扮演
顾姐|female|gujie|角色扮演
广告解说|male|guanggaojieshuo|通用场景
少儿故事|female|shaoergushi|有声阅读`;
export const voices: Voice[] = catalog.split('\n').map(row => {
  const [name, gender, key, tag] = row.split('|');
  return { id: `zh_${gender}_${key}_uranus_bigtts`, name, gender: gender === 'female' ? '女声' : '男声', tag, description: '豆包 2.0 · 支持风格描述与多语种', resource: 'seed-tts-2.0' };
});
for (const [name, gender, key] of [['Tim', 'male', 'tim'], ['Dacey', 'female', 'dacey'], ['Stokie', 'female', 'stokie']]) voices.push({ id: `en_${gender}_${key}_uranus_bigtts`, name, gender: gender === 'female' ? '女声' : '男声', tag: '外语音色', description: '豆包 2.0 · 美式英语', resource: 'seed-tts-2.0' });
